name: pl1_kasir
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  convex_bottom_bar: ^3.2.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  sliding_clipped_nav_bar: ^3.1.1
  supabase_flutter: ^2.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - img/logo.png
    - img/background.png
    - img/blob.svg
    - img/google.png
    - img/facebook.png
    - img/twitter.png
    - img/background_menu.png

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Regular.ttf
        - asset: fonts/Poppins/Poppins-Bold.ttf
    
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Regular.ttf
        - asset: fonts/Roboto/Roboto-Bold.ttf